version: '3.8'

services:
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=todo_db
    networks:
      - webnet  
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_db

    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge